## Pair of functions that cache the inverse of a matrix. 
## Example of use : 
## m <- matrix(1:4, 2, 2)               
## # create a special wrapper around the matrix
## mWithCache <- makeCacheMatrix(m) 
## # calling cacheSolve will solve the matrix and store its result in cache
## cacheSolve(m)             
## # calling cacheSolve will return the previous result from the cache
## cacheSolve(m)             
## getting cached inverse 

## This function creates a special matrix that can cache its inverse. 
## Parameters : 
## - x : the initial matrix that will be wrapped in the special matrix 
##         with cache
##
## Return a list providing the following functions : 
##  - get : return the matrix
##  - set(y) : set the matrix
##  - getInverse() : return the inverse of the matrix
##  - setInverse(i) : set the inverse of the matrix
makeCacheMatrix <- function(x = matrix()) {
    inverse <- NULL
    set <- function(y) {
        x <<- y
        inverse <<- NULL
    }
    get <- function() x
    setInverse <- function(newInverse) inverse <<- newInverse
    getInverse <- function() inverse
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## Compute the inverse of a matrix with a cache. 
## This method returns the cached inverser of the matrix if the inverse
## has alread been computed on that matrix. 
## 
## Parameters : 
## - x : the matrix to inverse. This must be a matrix generated by 
##         the makeCacheMatrix function
## - ... : additional arguments given to the solve function
cacheSolve <- function(x, ...) {
    i <- x$getInverse()
    if(!is.null(i)) {
        message("getting cached inverse")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setInverse(i)
    i
}

